config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  resources :beers do
    resources :beer_comments
    resources :ingredients
    post 'like', :to => 'ratings#create'
    post 'dislike', :to => 'ratings#dislike'
  end

  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/beer.rb
class Beer < ActiveRecord::Base
	has_many :beer_comments, :dependent => :destroy
	has_many :ingredients, :dependent => :destroy
	has_many :ratings, :dependent => :destroy
end

app/models/beer_comment.rb
class BeerComment < ActiveRecord::Base
  belongs_to :beer
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  belongs_to :beer
end

app/models/rating.rb
class Rating < ActiveRecord::Base
  belongs_to :beer
  validates_uniqueness_of :user_id, :scope => :beer_id
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/beer_comments_controller.rb
class BeerCommentsController < InheritedResources::Base
	def new
		@beer = Beer.find(params[:beer_id])
		@beer_comment = @beer.beer_comments.build
	end

	def create
		@beer = Beer.find(params[:beer_id])
		@beer_comment = @beer.beer_comments.new(beer_comment_params)
		@beer_comment.user_id = current_user.id
		if @beer_comment.save
			redirect_to @beer, :notice => 'Comment added!'
		else
			render :new
		end
	end
  private

    def beer_comment_params
      params.require(:beer_comment).permit(:beer_id, :body, :user_id)
    end
end

app/controllers/beers_controller.rb
class BeersController < InheritedResources::Base
	before_action :authenticate_user!
	def index
		@beers = Beer.all
	end

	def show
		@beer = Beer.find(params[:id])
		@comments = @beer.beer_comments
		@ratings = @beer.ratings.all
		@likesArray = Array.new
		@dislikesArray = Array.new
		@ratings.each do |rating|
			if rating.like
				@likesArray.push(rating)
			else
				@dislikesArray.push(rating)
			end
		end
		@likes = @likesArray.count
		@dislikes = @dislikesArray.count
	end

	def new
		@beer = Beer.new
	end

	def create
		@beer = Beer.new(beer_params)
		@beer.added_by = current_user.id
		respond_to do |format|
			if @beer.save
				format.html { redirect_to beers_path, notice: 'Created beer!'}
			else
				format.html { render :new }
			end
		end
	end

	def like
		@beer = Beer.find(params[:beer_id])
		@rating = @beer.ratings.build
		@rating.beer_id = @beer
		@rating.user_id = current_user.id
		@rating.like = true
		if @rating.save
			redirect_to @beer, notice: 'Thanks for the feedback!'
		else
			redirect_to @beer, error: 'uhh... yeaaah.... something bad happened'
		end
	end

	def dislike
		@beer = Beer.find(params[:beer_id])
		@rating = @beer.ratings.new
		@rating.beer_id = @beer
		@rating.user_id = current_user.id
		@rating.like = false
		if @rating.save
			redirect_to @beer, notice: 'Thanks for the feedback!'
		else
			redirect_to @beer, error: 'Apparently it doesnt want to be disliked.  Try again'
		end
	end
  private
    def beer_params
      params.require(:beer).permit(:name, :description, :og, :fg, :abv, :color, :instructions, :added_by)
    end
end

app/controllers/ingredients_controller.rb
class IngredientsController < InheritedResources::Base
	def new
		@beer = Beer.find(params[:beer_id])
		@ingredient = @beer.ingredients.build
	end

	def create
		@beer = Beer.find(params[:beer_id])
		@ingredient = @beer.ingredients.new(ingredient_params)
		if @ingredient.save
			redirect_to @beer, notice: 'ingredient added'
		else
			redirect_to @beer, notice: 'error'
		end
	end
  private

    def ingredient_params
      params.require(:ingredient).permit(:beer_id, :qty, :measurement, :name)
    end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
	def new
		@beer = Beer.find(params[:beer_id])
		@rating = @beer.ratings.build
	end

	def create
		@beer = Beer.find(params[:beer_id])
		@like = true
		@user = current_user.id
		@rating = @beer.ratings.build
		@rating.like = @like
		@rating.user_id = @user
		if @rating.save
			redirect_to @beer, notice: 'Liked'
		else
			redirect_to @beer, notice: 'Nope.  Like didnt work'
		end
	end

	def dislike
		@beer = Beer.find(params[:beer_id])
		@like = false
		@user = current_user.id
		@rating = @beer.ratings.build
		@rating.like = @like
		@rating.user_id = @user
		if @rating.save
			redirect_to @beer, notice: 'Disliked'
		else
			redirect_to @beer, notice: 'Nope.  Dislike didnt work'
		end
	end

	private
	def ratings_params
		params.permit(:beer_id, :user_id, :like)
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/beer_comments_helper.rb
module BeerCommentsHelper
end

app/helpers/beer_ratings_helper.rb
module BeerRatingsHelper
end

app/helpers/beers_helper.rb
module BeersHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/beer_comments/_form.html.erb
<%= form_for([@beer, @beer_comment]) do |f| %>
  <% if @beer_comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@beer_comment.errors.count, "error") %> prohibited this beer_comment from being saved:</h2>

      <ul>
      <% @beer_comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/beer_comments/edit.html.erb
<h1>Editing Beer Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @beer_comment %> |
<%= link_to 'Back', beer_comments_path %>

app/views/beer_comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Beer Comments</h1>

<table>
  <thead>
    <tr>
      <th>Beer</th>
      <th>Like</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @beer_comments.each do |beer_comment| %>
      <tr>
        <td><%= beer_comment.beer %></td>
        <td><%= beer_comment.like %></td>
        <td><%= beer_comment.user_id %></td>
        <td><%= link_to 'Show', beer_comment %></td>
        <td><%= link_to 'Edit', edit_beer_comment_path(beer_comment) %></td>
        <td><%= link_to 'Destroy', beer_comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Beer comment', new_beer_comment_path %>

app/views/beer_comments/new.html.erb
<h1>New Beer Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', @beer %>

app/views/beer_comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Beer:</strong>
  <%= @beer_comment.beer %>
</p>

<p>
  <strong>Like:</strong>
  <%= @beer_comment.like %>
</p>

<p>
  <strong>User:</strong>
  <%= @beer_comment.user_id %>
</p>

<%= link_to 'Edit', edit_beer_comment_path(@beer_comment) %> |
<%= link_to 'Back', beer_comments_path %>

app/views/beers/_form.html.erb
<%= form_for(@beer) do |f| %>
  <% if @beer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@beer.errors.count, "error") %> prohibited this beer from being saved:</h2>

      <ul>
      <% @beer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :og %><br>
    <%= f.text_field :og %>
  </div>
  <div class="field">
    <%= f.label :fg %><br>
    <%= f.text_field :fg %>
  </div>
  <div class="field">
    <%= f.label :abv %><br>
    <%= f.text_field :abv %>
  </div>
  <div class="field">
    <%= f.label :color %><br>
    <%= f.text_field :color %>
  </div>
  <div class="field">
    <%= f.label :instructions %><br>
    <%= f.text_area :instructions %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/beers/edit.html.erb
<h1>Editing Beer</h1>

<%= render 'form' %>

<%= link_to 'Show', @beer %> |
<%= link_to 'Back', beers_path %>

app/views/beers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Beers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Abv</th>
      <th>Added by</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @beers.each do |beer| %>
      <tr>
        <td><%= beer.name %></td>
        <td><%= beer.abv %></td>
        <td><%= User.find(beer.added_by).email %></td>
        <td><%= link_to 'Show', beer %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Beer', new_beer_path %>

app/views/beers/new.html.erb
<h1>New Beer</h1>

<%= render 'form' %>

<%= link_to 'Back', beers_path %>

app/views/beers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @beer.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @beer.description %>
</p>

<p>
  <strong>Og:</strong>
  <%= @beer.og %>
</p>

<p>
  <strong>Fg:</strong>
  <%= @beer.fg %>
</p>

<p>
  <strong>Abv:</strong>
  <%= @beer.abv %>
</p>

<p>
  <strong>Color:</strong>
  <%= @beer.color %>
</p>

<p>
  <strong>Instructions:</strong>
  <%= @beer.instructions %>
</p>

<p>
  <strong>Added by:</strong>
  <%= User.find(@beer.added_by).email %>
</p>

<p>
<strong><%= link_to 'Likes:', beer_like_path(@beer), method: :post %> </strong><%= @likes %>
<strong><%= link_to 'Dislikes:', beer_dislike_path(@beer), method: :post %> </strong><%= @dislikes %>
</p>
<hr>
<h3>Ingredients</h3>
<ul> 
  <% if @beer.ingredients %>
    <% @beer.ingredients.each do |ingredient| %>
      <li><%= ingredient.qty %> <%= ingredient.measurement %> <%= ingredient.name %> </li>
    <% end %>
  <% else %>
    <li>No ingredients yet!</li>
  <% end %>
</ul>
<% if @beer.added_by == current_user.id %>
 <%= link_to 'Add Ingredient', new_beer_ingredient_path(@beer) %>
<% end %>
<hr>
<h3>Comments</h3>
<%= link_to 'New Comment', new_beer_beer_comment_path(@beer) %>
<% if !@beer.beer_comments %>
  <p>No comments</p>
<% else %>
  <% @beer.beer_comments.each do |comment| %>
    <h4><%= User.find(comment.user_id).email %><h4>
    <p><%= comment.body%></p>
    <br/>
  <% end %>
<%= link_to 'Back', beers_path %>
<% end %>

app/views/ingredients/_form.html.erb
<%= form_for([@beer,@ingredient]) do |f| %>
  <% if @ingredient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ingredient.errors.count, "error") %> prohibited this ingredient from being saved:</h2>

      <ul>
      <% @ingredient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :qty %><br>
    <%= f.text_field :qty %>
  </div>
  <div class="field">
    <%= f.label :measurement %><br>
    <%= f.text_field :measurement %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ingredients/edit.html.erb
<h1>Editing Ingredient</h1>

<%= render 'form' %>

<%= link_to 'Show', @ingredient %> |
<%= link_to 'Back', ingredients_path %>

app/views/ingredients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Ingredients</h1>

<table>
  <thead>
    <tr>
      <th>Beer</th>
      <th>Qty</th>
      <th>Measurement</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ingredients.each do |ingredient| %>
      <tr>
        <td><%= ingredient.beer %></td>
        <td><%= ingredient.qty %></td>
        <td><%= ingredient.measurement %></td>
        <td><%= ingredient.name %></td>
        <td><%= link_to 'Show', ingredient %></td>
        <td><%= link_to 'Edit', edit_ingredient_path(ingredient) %></td>
        <td><%= link_to 'Destroy', ingredient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ingredient', new_ingredient_path %>

app/views/ingredients/new.html.erb
<h1>New Ingredient</h1>

<%= render 'form' %>

<%= link_to 'Back', @beer %>

app/views/ingredients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Qty:</strong>
  <%= @ingredient.qty %>
</p>

<p>
  <strong>Measurement:</strong>
  <%= @ingredient.measurement %>
</p>

<p>
  <strong>Name:</strong>
  <%= @ingredient.name %>
</p>

<%= link_to 'Back', ingredients_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BeerMe!</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h2>Welcome!</h2>
<p>Welcome to the BeerMe! web interface!  Here you can view and add to the list of beer recipes that you can brew and rate for yourself!
</p>
<p>
<%= link_to 'Check them out!', beers_path %>
</p>